In [3]:
import pandas as pd

data = {
    "id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "user_id": [101, 102, 101, 103, 102, 104, 101, 103, 104, 102, 101, 105],
    "category": ["Electronics", "Fashion", "Electronics", "Electronics", "Fashion", 
                 "Fashion", "Food", "Electronics", "Electronics", "Food", "Electronics", "Fashion"],
    "amount": [1500000,250000,1500000,750000,180000,250000,
               45000,1500000,750000,45000,1500000,250000],
    "status": ["completed","completed","completed","completed",
               "cancelled","completed","completed","completed",
               "completed","completed","completed","completed"],
    "created_at": pd.to_datetime([
        "2024-01-05","2024-01-06","2024-01-05","2024-01-07",
        "2024-01-08","2024-01-09","2024-01-10","2024-01-11",
        "2024-01-12","2024-01-13","2024-01-05","2024-01-14"
    ])
}

df = pd.DataFrame(data)
df.head()

   id  user_id     category   amount     status created_at
0   1      101  Electronics  1500000  completed 2024-01-05
1   2      102      Fashion   250000  completed 2024-01-06
2   3      101  Electronics  1500000  completed 2024-01-05
3   4      103  Electronics   750000  completed 2024-01-07
4   5      102      Fashion   180000  cancelled 2024-01-08

In [26]:
# GP-1 — Tampilkan hanya transaksi completed, pilih kolom user_id, category, amount saja.
# Hint: dua operasi terpisah — filter dulu, baru pilih kolom
completed_trx = df[df["status"] == "completed"]
completed_trx = completed_trx[["user_id", "category", "amount"]]
completed_trx

    user_id     category   amount
0       101  Electronics  1500000
1       102      Fashion   250000
2       101  Electronics  1500000
3       103  Electronics   750000
5       104      Fashion   250000
6       101         Food    45000
7       103  Electronics  1500000
8       104  Electronics   750000
9       102         Food    45000
10      101  Electronics  1500000
11      105      Fashion   250000

In [32]:
# GP-2 — Dari hasil GP-1, hitung total revenue dan jumlah transaksi per category. Urutkan dari revenue tertinggi.
# Hint: groupby().agg() dengan dua fungsi sekaligus
revenue_category = completed_trx.groupby("category").agg(
    total_revenue=("amount", "sum"),
    total_trx=("user_id", "count")
)
revenue_category = revenue_category. \
                    reset_index(). \
                    sort_values("total_revenue", ascending=False)
revenue_category

      category  total_revenue  total_trx
0  Electronics        7500000          6
1      Fashion         750000          3
2         Food          90000          2

In [29]:
# GP-3 — Tambahkan kolom amount_millions ke DataFrame original yang berisi amount dibagi 1.000.000, bulatkan 2 desimal.
# Hint: round() bisa dichain langsung — (df["amount"] / 1_000_000).round(2)
df["amount_millions"] = (df["amount"] / 1_000_000).round(2)
df

    id  user_id     category   amount     status created_at  amount_millions
0    1      101  Electronics  1500000  completed 2024-01-05             1.50
1    2      102      Fashion   250000  completed 2024-01-06             0.25
2    3      101  Electronics  1500000  completed 2024-01-05             1.50
3    4      103  Electronics   750000  completed 2024-01-07             0.75
4    5      102      Fashion   180000  cancelled 2024-01-08             0.18
5    6      104      Fashion   250000  completed 2024-01-09             0.25
6    7      101         Food    45000  completed 2024-01-10             0.04
7    8      103  Electronics  1500000  completed 2024-01-11             1.50
8    9      104  Electronics   750000  completed 2024-01-12             0.75
9   10      102         Food    45000  completed 2024-01-13             0.04
10  11      101  Electronics  1500000  completed 2024-01-05             1.50
11  12      105      Fashion   250000  completed 2024-01-14             0.25

In [43]:
import numpy as np

df_dirty = df.copy()
df_dirty.loc[2, "amount"] = np.nan
df_dirty.loc[5, "category"] = None
df_dirty.loc[8, "user_id"] = np.nan
df_dirty

    id  user_id     category     amount     status created_at  amount_millions
0    1    101.0  Electronics  1500000.0  completed 2024-01-05             1.50
1    2    102.0      Fashion   250000.0  completed 2024-01-06             0.25
2    3    101.0  Electronics        NaN  completed 2024-01-05             1.50
3    4    103.0  Electronics   750000.0  completed 2024-01-07             0.75
4    5    102.0      Fashion   180000.0  cancelled 2024-01-08             0.18
5    6    104.0          NaN   250000.0  completed 2024-01-09             0.25
6    7    101.0         Food    45000.0  completed 2024-01-10             0.04
7    8    103.0  Electronics  1500000.0  completed 2024-01-11             1.50
8    9      NaN  Electronics   750000.0  completed 2024-01-12             0.75
9   10    102.0         Food    45000.0  completed 2024-01-13             0.04
10  11    101.0  Electronics  1500000.0  completed 2024-01-05             1.50
11  12    105.0      Fashion   250000.0  completed 2024-01-14             0.25

In [44]:
print(df_dirty.isna().sum())

id                 0
user_id            1
category           1
amount             1
status             0
created_at         0
amount_millions    0
dtype: int64

In [46]:
# GP-4 — Sekarang handle missing values-nya:
# Kolom amount yang NULL → isi dengan 0
# Kolom category yang NULL → isi dengan string "unknown"
# Baris yang user_id-nya NULL → hapus baris tersebut
# Hint: fillna() untuk isi, dropna() untuk hapus — keduanya punya parameter subset untuk spesifik kolom

df_dirty["amount"] = df_dirty["amount"].fillna(0)
df_dirty["category"] = df_dirty["category"].fillna("unknown")
df_dirty = df_dirty.dropna(subset=["user_id"])
df_dirty

    id  user_id     category     amount     status created_at  amount_millions
0    1    101.0  Electronics  1500000.0  completed 2024-01-05             1.50
1    2    102.0      Fashion   250000.0  completed 2024-01-06             0.25
2    3    101.0  Electronics        0.0  completed 2024-01-05             1.50
3    4    103.0  Electronics   750000.0  completed 2024-01-07             0.75
4    5    102.0      Fashion   180000.0  cancelled 2024-01-08             0.18
5    6    104.0      Unknown   250000.0  completed 2024-01-09             0.25
6    7    101.0         Food    45000.0  completed 2024-01-10             0.04
7    8    103.0  Electronics  1500000.0  completed 2024-01-11             1.50
9   10    102.0         Food    45000.0  completed 2024-01-13             0.04
10  11    101.0  Electronics  1500000.0  completed 2024-01-05             1.50
11  12    105.0      Fashion   250000.0  completed 2024-01-14             0.25

In [47]:
df_dirty.isna().sum()

id                 0
user_id            0
category           0
amount             0
status             0
created_at         0
amount_millions    0
dtype: int64

In [48]:
users = pd.DataFrame({
    "user_id": [101, 102, 103, 104, 105, 106],
    "name": ["Budi", "Ani", "Citra", "Deni", "Eko", "Fani"],
    "tier": ["gold", "silver", "gold", "bronze", "silver", "gold"]
})

In [52]:
# GP-5 — Merge (JOIN di pandas)
# Gabungkan df (completed transactions saja) dengan users — semua user harus tampil meskipun tidak punya transaksi.
# Hint: pd.merge(left, right, on="kolom", how="...") — pilih how yang tepat

completed_trx = df[df["status"] == "completed"]
users_completed_trx = pd.merge(users, completed_trx, on="user_id", how="left")
users_completed_trx

,user_id,name,tier,id,category,amount,status,created_at,amount_millions
0,101,Budi,gold,1.0,Electronics,1500000.0,completed,2024-01-05,1.50
1,101,Budi,gold,3.0,Electronics,1500000.0,completed,2024-01-05,1.50
2,101,Budi,gold,7.0,Food,45000.0,completed,2024-01-10,0.04
3,101,Budi,gold,11.0,Electronics,1500000.0,completed,2024-01-05,1.50
4,102,Ani,silver,2.0,Fashion,250000.0,completed,2024-01-06,0.25
5,102,Ani,silver,10.0,Food,45000.0,completed,2024-01-13,0.04
6,103,Citra,gold,4.0,Electronics,750000.0,completed,2024-01-07,0.75
7,103,Citra,gold,8.0,Electronics,1500000.0,completed,2024-01-11,1.50
8,104,Deni,bronze,6.0,Fashion,250000.0,completed,2024-01-09,0.25
9,104,Deni,bronze,9.0,Electronics,750000.0,completed,2024-01-12,0.75
10,105,Eko,silver,12.0,Fashion,250000.0,completed,2024-01-14,0.25
11,106,Fani,gold,NaN,NaN,NaN,NaN,NaT,NaN

In [54]:
def categorize_amount(amount):
    if amount >= 1000000:
        return "large"
    elif amount >= 200000:
        return "medium"
    else:
        return "small"
df["size"] = df["amount"].apply(categorize_amount)

# bisa juga dengan lambda (anonymous func) jika hanya ingin simple function
# df["size"] = df["amount"].apply(lambda x: "large" if x > 1000000 else "small")

,id,user_id,category,amount,status,created_at,amount_millions,size
0,1,101,Electronics,1500000,completed,2024-01-05,1.50,large
1,2,102,Fashion,250000,completed,2024-01-06,0.25,medium
2,3,101,Electronics,1500000,completed,2024-01-05,1.50,large
3,4,103,Electronics,750000,completed,2024-01-07,0.75,medium
4,5,102,Fashion,180000,cancelled,2024-01-08,0.18,small
5,6,104,Fashion,250000,completed,2024-01-09,0.25,medium
6,7,101,Food,45000,completed,2024-01-10,0.04,small
7,8,103,Electronics,1500000,completed,2024-01-11,1.50,large
8,9,104,Electronics,750000,completed,2024-01-12,0.75,medium
9,10,102,Food,45000,completed,2024-01-13,0.04,small
10,11,101,Electronics,1500000,completed,2024-01-05,1.50,large
11,12,105,Fashion,250000,completed,2024-01-14,0.25,medium

In [55]:
# GP-6 — Tambahkan kolom revenue_segment ke df berdasarkan rules ini:
# amount >= 1.000.000 → "premium"
# amount >= 200.000 → "standard"
# amount < 200.000 → "low"

def categorize_segment(amount):
    if amount >= 1000000:
        return "premium"
    elif amount >= 200000:
        return "standard"
    else:
        return "low"
        
df["revenue_segment"] = df["amount"].apply(categorize_segment)
df

,id,user_id,category,amount,status,created_at,amount_millions,size,revenue_segment
0,1,101,Electronics,1500000,completed,2024-01-05,1.50,large,premium
1,2,102,Fashion,250000,completed,2024-01-06,0.25,medium,standard
2,3,101,Electronics,1500000,completed,2024-01-05,1.50,large,premium
3,4,103,Electronics,750000,completed,2024-01-07,0.75,medium,standard
4,5,102,Fashion,180000,cancelled,2024-01-08,0.18,small,low
5,6,104,Fashion,250000,completed,2024-01-09,0.25,medium,standard
6,7,101,Food,45000,completed,2024-01-10,0.04,small,low
7,8,103,Electronics,1500000,completed,2024-01-11,1.50,large,premium
8,9,104,Electronics,750000,completed,2024-01-12,0.75,medium,standard
9,10,102,Food,45000,completed,2024-01-13,0.04,small,low
10,11,101,Electronics,1500000,completed,2024-01-05,1.50,large,premium
11,12,105,Fashion,250000,completed,2024-01-14,0.25,medium,standard